name: ci-cd.yml
on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: ${{ secrets.DB_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        ports:
          - 5432:5432
        # Health check ensures DB is ready before tests start
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'zulu'
          cache: maven
          cache-dependency-path: ./backend/pom.xml

      - name: Build and Install API Module
        run: |
          ./mvnw clean install -pl open-fashion-api_v1 -am -DskipTests

      - name: Build and Test Entire Project
        run: ./mvnw clean verify

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: ${{ !env.ACT }}
        with:
          report_paths: '**/backend/**/target/surefire-reports/TEST-*.xml'

  #CD STAGE: Docked Build & Push (only runs on main if tests pass)
  docker-build:
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: 25
          distribution: 'zulu'
          cache: maven

      - name: Build Application Jar
        run: ./mvnw clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend/open-fashion-backend
          file: ./backend/open-fashion-backend/Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/open-fashion-backend